let
    Source = List.Dates(StartDate, Length, #duration(1, 0, 0, 0)),
    #"Converted to Table" = Table.FromList(Source, Splitter.SplitByNothing(), null, null, ExtraValues.Error),
    #"Renamed Columns" = Table.RenameColumns(#"Converted to Table",{{"Column1", "Date"}}),
    #"Changed Type" = Table.TransformColumnTypes(#"Renamed Columns",{{"Date", type date}}),
    StartDate = #date(2023, 1, 1),
    Today = #date(2024, 7, 19),
    Length = Duration.Days(Today - StartDate),
    Custom1 = #"Changed Type",
    #"Inserted Year" = Table.AddColumn(Custom1, "Year", each Date.Year([Date]), Int64.Type),
    #"Inserted Month Name" = Table.AddColumn(#"Inserted Year", "Month Name", each Date.MonthName([Date]), type text),
    #"Inserted Day Name" = Table.AddColumn(#"Inserted Month Name", "Day Name", each Date.DayOfWeekName([Date]), type text),
    #"Inserted Month" = Table.AddColumn(#"Inserted Day Name", "Month", each Date.Month([Date]), Int64.Type),
    #"Inserted Day of Week" = Table.AddColumn(#"Inserted Month", "Day of Week", each Date.DayOfWeek(([Date]), Day.Monday)+1, Int64.Type),
    #"Inserted First Characters" = Table.AddColumn(#"Inserted Day of Week", "MMM", each Text.Start([Month Name], 3), type text),
    #"Inserted First Characters1" = Table.AddColumn(#"Inserted First Characters", "DDD", each Text.Start([Day Name], 3), type text),
    #"Reordered Columns" = Table.ReorderColumns(#"Inserted First Characters1",{"Date", "Year", "Month Name", "MMM", "Month", "Day Name", "DDD", "Day of Week"}),
    #"Added Custom" = Table.AddColumn(#"Reordered Columns", "YYMM", each ([Year]-2000)*100 + [Month]),
    #"Added Custom1" = Table.AddColumn(#"Added Custom", "MonthID", each (Date.Year([Date]) - Date.Year(StartDate))*12 + Date.Month([Date])),
    #"Added Custom2" = Table.AddColumn(#"Added Custom1", "DayMonthText", each Date.ToText( [Date], [Format = "dd MMM" ] )),
    #"Added Custom3" = Table.AddColumn(#"Added Custom2", "DayMonthInt", each Date.ToText( [Date], [Format = "dd" ] )),
    #"Added Custom4" = Table.AddColumn(#"Added Custom3", "YearMonthShort", each Text.Combine( 
    {
        Date.ToText( [Date], [Format = "MMM" ] ),
        Date.ToText( [Date], [Format = "yy" ] )
    }, 
    "'" 
)),
    #"Added Custom5" = Table.AddColumn(#"Added Custom4", "YearMonthLong", each Text.Combine( 
    {   Date.ToText( [Date], [Format = "yyyy" ] ),
        Date.ToText( [Date], [Format = "MMMM" ] )
    }, 
    " " 
)),
    #"Added Custom6" = Table.AddColumn(#"Added Custom5", "QuarterInt", each Date.QuarterOfYear([Date])),
    #"Added Custom7" = Table.AddColumn(#"Added Custom6", "QuarterText", each Text.Combine( {"Q", Text.From([QuarterInt]) }, "" )),
    #"Added Custom8" = Table.AddColumn(#"Added Custom7", "WeekOfYearInt", each Date.WeekOfYear([Date])),
    #"Added Custom10" = Table.AddColumn(#"Added Custom8", "WeekOfYearText", each Text.Combine(
    {
      "W",
      Text.From([WeekOfYearInt])
    },
    ""
)),
    #"Added Custom9" = Table.AddColumn(#"Added Custom10", "WeekOfMonth", each Date.WeekOfMonth( [Date] )),
    #"Added Custom11" = Table.AddColumn(#"Added Custom9", "YearQuarter", each Text.Combine( 
    {
        [QuarterText],
        Date.ToText( [Date], [Format = "yy" ] )
    }, 
    "'" 
)),
    #"Added Custom12" = Table.AddColumn(#"Added Custom11", "Custom", each Text.Combine( 
    {
        Date.ToText( [Date], [Format = "yyyy" ] ),
        Text.From([QuarterInt])
    }, 
    "" 
)),
    #"Changed Type3" = Table.TransformColumnTypes(#"Added Custom12",{{"Custom", Int64.Type}}),
    #"Changed Type1" = Table.TransformColumnTypes(#"Changed Type3",{{"DayMonthInt", Int64.Type}}),
    #"Sorted Rows" = Table.Sort(#"Changed Type1",{{"Date", Order.Descending}}),
    #"Renamed Columns1" = Table.RenameColumns(#"Sorted Rows",{{"Month Name", "MonthLong"}, {"MMM", "MonthShort"}, {"Month", "MonthInt"}, {"Day Name", "DayLong"}, {"DDD", "DayShort"}, {"Day of Week", "DayInt"}}),
    #"Reordered Columns1" = Table.ReorderColumns(#"Renamed Columns1",{"Date", "DayMonthInt", "DayMonthText", "Year", "MonthLong", "MonthShort", "MonthInt", "DayLong", "DayShort", "DayInt", "YYMM", "MonthID"}),
    #"Changed Type2" = Table.TransformColumnTypes(#"Reordered Columns1",{{"QuarterInt", Int64.Type}}),
    #"Sorted Rows1" = Table.Sort(#"Changed Type2",{{"Date", Order.Descending}}),
    #"Renamed Columns2" = Table.RenameColumns(#"Sorted Rows1",{{"Custom", "YearQuarterInt"}, {"DayLong", "WeekDayLong"}, {"DayShort", "WeekDayShort"}, {"DayInt", "WeekDayInt"}})
in
    #"Renamed Columns2"
